export const FETCH_STG_SUCCESS = "FETCH_STG_SUCCESS";
export const ADD_STG_SUCCESS = "ADD_STG_SUCCESS";
export const DELETE_STG_SUCCESS = "DELETE_STG_SUCCESS";
export const FETCH_CLASSIFIERS_SUCCESS = "FETCH_CLASSIFIERS_SUCCESS";
