export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_CLASSIFIERS_SUCCESS = "FETCH_CLASSIFIERS_SUCCESS";
export const UPDATE_SELF_SUCCESS = "UPDATE_SELF_SUCCESS";
