export const FETCH_EXAMS_SUCCESS = "FETCH_EXAMS_SUCCESS";
export const ADD_EXAM_SUCCESS = "ADD_EXAM_SUCCESS";
export const UPDATE_EXAM_SUCCESS = "ADD_EXAM_SUCCESS";
export const FETCH_CLASSIFIERS_SUCCESS = "FETCH_CLASSIFIERS_SUCCESS";
