export const FETCH_EXAMS_SUCCESS = "FETCH_EXAMS_SUCCESS";
export const ADD_EXAM_SUCCESS = "ADD_EXAM_SUCCESS";
export const UPDATE_EXAM_SUCCESS = "ADD_EXAM_SUCCESS";
export const FETCH_STUDENTS_SUCCESS = "FETCH_STUDENTS_SUCCESS";
export const FETCH_EXAM_SUCCESS = "FETCH_EXAM_SUCCESS";
export const SET_SESSION_LOADING = "SET_SESSION_LOADING";
